# Generated by Django 3.0.8 on 2020-07-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': 'pessoas',
            },
        ),
    ]
