# Generated by Django 3.0.8 on 2020-07-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='id_pessoa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
